# Generated by Django 5.0 on 2023-12-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Travel', 'Travel'), ('Adventure', 'Adventure'), ('Fun', 'Fun'), ('Creative', 'Creative'), ('Skills', 'Skills'), ('Fitness', 'Fitness'), ('Personal', 'Personal'), ('Finance', 'Finance')], max_length=50)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
